version: '3.8'

services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      # Уникальный ID узла
      - KAFKA_NODE_ID=1

      # Включаем роли broker и controller для KRaft
      - KAFKA_PROCESS_ROLES=broker,controller

      # Настройка слушателей (listeners)
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093

      # Реклама адресов (advertised listeners)
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://broker:29092,CONTROLLER://broker:9093

      # Протоколы безопасности для listeners
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Выбираем listener для внутреннего общения брокеров
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

      # Настройки контроллера KRaft
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker:9093

      # Конфигурация топиков и групп
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3

      # Автоматическое создание топиков (опционально)
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

    volumes:
      - kafka-data:/var/lib/kafka/data

    networks:
      - kafka-network

volumes:
  kafka-data:

networks:
  kafka-network:
    driver: bridge
