server:
  port: 8082

spring:
  application:
    name: order-query-service

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-query-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "cz.cvut.fel.nss.orderqueryservice.event"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/order-management
          jwk-set-uri: http://localhost:8080/realms/order-management/protocol/openid-connect/certs

hazelcast:
  network:
    join:
      multicast:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    cz.cvut.fel.nss: DEBUG
    org.springframework.data.elasticsearch: INFO
    org.springframework.graphql: DEBUG 